setup:
  feature_enabled: true # if you dont want it to listen to emails then set this to false
  username: 'username'
  password: 'password'
  repository_owner: 'repository_owner'
  repository_name: 'repository_name'