setup:
  feature_enabled: true # if you dont want it to listen to emails then set this to false
  pop3_address: "pop.gmail.com"
  pop3_username: "username"
  pop3_password: "password"
  pop3_port: 995
  pop3_enable_ssl: true
  reciever_filter: "digitaleseiten.de" # which domains are relevant for getting messages from - leave empty if you dont care

